import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { brand, origin, home, pages, shareImage } from '../content/pages.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../public');
const escape = value => value.replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
const url = path => origin + path;

function metadata(page) {
  const canonical = url(page.path);
  const graph = [
    { '@type': 'Organization', '@id': url('/#organization'), name: brand, url: url('/'),
      logo: { '@type': 'ImageObject', url: url('/assets/icon-512.png'), width: 512, height: 512 }, email: 'info@inrsettle.com' },
    { '@type': 'WebSite', '@id': url('/#website'), name: brand, url: url('/'),
      inLanguage: 'en', publisher: { '@id': url('/#organization') } },
    { '@type': 'WebPage', '@id': canonical + '#webpage', url: canonical, name: page.title,
      description: page.description, inLanguage: 'en', isPartOf: { '@id': url('/#website') },
      about: { '@id': url('/#organization') } },
  ];
  if (page.path !== '/') {
    const crumbs = [{ name: brand, item: url('/') }];
    if (page.parent) crumbs.push({ name: pages.find(item => item.path === page.parent).label, item: url(page.parent) });
    crumbs.push({ name: page.label, item: canonical });
    graph.push({ '@type': 'BreadcrumbList', '@id': canonical + '#breadcrumbs',
      itemListElement: crumbs.map((crumb, index) => ({ '@type': 'ListItem', position: index + 1, ...crumb })) });
    graph[2].breadcrumb = { '@id': canonical + '#breadcrumbs' };
  }
  const schema = JSON.stringify({ '@context': 'https://schema.org', '@graph': graph }).replaceAll('<', '\\u003c');
  return `  <!-- Generated by landing/scripts/build-seo.mjs; edit landing/content/pages.mjs. -->
  <title>${escape(page.title)}</title>
  <meta name="description" content="${escape(page.description)}">
  <meta name="robots" content="index, follow, max-image-preview:large">
  <link rel="canonical" href="${canonical}">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="${brand}">
  <meta property="og:locale" content="en_IN">
  <meta property="og:title" content="${escape(page.title)}">
  <meta property="og:description" content="${escape(page.description)}">
  <meta property="og:url" content="${canonical}">
  <meta property="og:image" content="${url(shareImage)}">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta property="og:image:type" content="image/png">
  <meta property="og:image:alt" content="INRSettle — cross-border settlement infrastructure for India">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="${escape(page.title)}">
  <meta name="twitter:description" content="${escape(page.description)}">
  <meta name="twitter:image" content="${url(shareImage)}">
  <meta name="twitter:image:alt" content="INRSettle — cross-border settlement infrastructure for India">
  <script type="application/ld+json">${schema}</script>`;
}

function navigation(current, footer = false) {
  return pages.filter(page => footer || !page.parent && page.path !== '/privacy').map(page =>
    `<a href="${page.path}"${current === page.path ? ' aria-current="page"' : ''}>${page.label}</a>`).join('');
}

function document(page) {
  const breadcrumb = `<a href="/">Home</a>${page.parent ? `<span aria-hidden="true">/</span><a href="${page.parent}">Documentation</a>` : ''}<span aria-hidden="true">/</span><span aria-current="page">${page.label}</span>`;
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#eef5fa">
${metadata(page)}
  <link rel="icon" type="image/svg+xml" href="/assets/brand-favicon.svg">
  <link rel="icon" type="image/x-icon" href="/assets/favicon.ico" sizes="16x16 32x32 48x48">
  <link rel="apple-touch-icon" href="/assets/icon-180.png">
  <link rel="stylesheet" href="/resources.css">
</head>
<body>
  <a class="skip-link" href="#main">Skip to content</a>
  <header class="resource-header"><a href="/" aria-label="INRSettle home"><img src="/assets/brand-lockup.svg" width="934" height="152" alt="INRSettle"></a><nav aria-label="Main navigation">${navigation(page.path)}</nav><a class="resource-button" href="/#contact-dialog">Talk to our team <span aria-hidden="true">→</span></a></header>
  <main id="main" class="resource-main">
    <nav class="breadcrumbs" aria-label="Breadcrumb">${breadcrumb}</nav>
    <div class="resource-intro"><p class="resource-eyebrow">${page.eyebrow}</p><h1>${page.heading}</h1><p>${page.intro}</p></div>
    ${page.body}
    <aside class="resource-cta"><p class="resource-eyebrow">From scope to integration</p><h2>Let’s define your India<br>settlement workflow.</h2><p>Bring your currencies, business use and operating requirements to a focused conversation with our team.</p><a class="resource-button" href="/#contact-dialog">Discuss your workflow <span aria-hidden="true">→</span></a></aside>
  </main>
  <footer class="resource-footer"><a href="/" aria-label="INRSettle home"><img src="/assets/brand-lockup.svg" width="934" height="152" alt="INRSettle"></a><nav aria-label="Footer navigation">${navigation(page.path, true)}</nav><a href="mailto:info@inrsettle.com">info@inrsettle.com</a></footer>
</body>
</html>
`;
}

const filename = path => resolve(root, '.' + (path === '/' ? '/index.html' : path + '/index.html'));
const mainFile = filename('/');
const main = await readFile(mainFile, 'utf8');
if (!main.includes('<!-- seo:start -->') || !main.includes('<!-- seo:end -->')) throw new Error('Home SEO markers are missing');
await writeFile(mainFile, main.replace(/  <!-- seo:start -->[\s\S]*?  <!-- seo:end -->/, `  <!-- seo:start -->\n${metadata(home)}\n  <!-- seo:end -->`));
for (const page of pages) {
  const file = filename(page.path);
  await mkdir(dirname(file), { recursive: true });
  await writeFile(file, document(page));
}
await writeFile(resolve(root, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${[home, ...pages].map(page => `  <url><loc>${url(page.path)}</loc></url>`).join('\n')}
</urlset>
`);
// Do not disallow /app: crawlers must be able to see its noindex response.
await writeFile(resolve(root, 'robots.txt'), `User-agent: *
Allow: /
Disallow: /api/

Sitemap: ${url('/sitemap.xml')}
`);
console.log(`SEO build: ${pages.length + 1} public pages, canonical metadata, sitemap and robots.txt.`);
