// Public explanations of the product model. These do not announce live API access,
// certifications, bank partnerships, prices or guaranteed corridor availability.
export const origin = 'https://www.inrsettle.com';
export const brand = 'INRSettle';
export const shareImage = '/assets/seo-share-20261002.png';
export const legacyRedirects = { '/legal/privacy': '/privacy', '/contact': '/#contact-dialog' };
export const home = {
  path: '/',
  title: 'INRSettle | Cross-Border Settlement Infrastructure for India',
  description: 'Connect INR, fiat and stablecoin settlement workflows for India. Coordinate liquidity, routing, payment requirements and reconciliation with INRSettle.',
};

export const pages = [
  {
    path: '/developers', label: 'Developers', eyebrow: 'Integration',
    title: 'India Settlement API & Integration | INRSettle',
    description: 'Explore the INRSettle integration model for India-linked settlement: beneficiaries, quotes, preflight, authorization, status updates and reconciliation.',
    heading: 'Connect your platform.<br><span>Keep the settlement clear.</span>',
    intro: 'Bring India-linked settlement into your payment product through a shared workflow for beneficiaries, quotes, authorization, execution status and reconciliation.',
    body: `<section><h2>A recipient-first settlement workflow</h2><p>Start with a verified Indian beneficiary, the exact INR amount the recipient should receive and the commercial purpose. Funding currency, payment requirements, FX and provider execution belong to the same settlement record.</p><ol class="resource-steps"><li><h3>Prepare the instruction</h3><p>Define beneficiary, recipient amount, purpose and your own reference. Check the requirements and quote before asking for authorization.</p></li><li><h3>Authorize and observe</h3><p>Keep creation and authorization as separate permissions. Follow the recorded state and address a specific requirement when action is needed.</p></li><li><h3>Reconcile the result</h3><p>Connect delivery evidence, provider references and the final receipt to your own operating records.</p></li></ol></section>
      <section><h2>Integration boundaries to agree</h2><div class="resource-grid"><article><h3>Workspace and environment</h3><p>Credentials are scoped to a workspace and environment. Sandbox and live records remain separate.</p></article><article><h3>Safe retries</h3><p>Use a stable idempotency key for each logical settlement creation or authorization. An uncertain provider outcome needs review before resubmission.</p></article><article><h3>Event delivery</h3><p>Verify webhook signatures, record event identifiers and tolerate duplicate deliveries. Your system should not infer finality from a single provider response.</p></article><article><h3>Evidence and receipts</h3><p>Retain settlement references and reconciliation outcomes so your team can trace the result after execution.</p></article></div></section>
      <section><h2>Plan an integration with our team</h2><p>Share your business role, jurisdictions, proposed funding currency, Indian destination, use case and indicative volume. We will discuss route eligibility, provider responsibilities, access and acceptance criteria.</p><p>The public workspace is a demonstration. API access, supported routes and commercial terms are confirmed during onboarding; this website does not issue production credentials or initiate payments.</p><a class="resource-link" href="/docs/integration">Review the provider integration model →</a></section>`,
  },
  {
    path: '/docs', label: 'Documentation', eyebrow: 'Settlement documentation',
    title: 'India Settlement Workflow & Documentation | INRSettle',
    description: 'Understand the INRSettle operating model: beneficiary verification, quotes, preflight, approval, provider execution, reconciliation and settlement receipts.',
    heading: 'Understand the workflow.<br><span>Follow the evidence.</span>',
    intro: 'A settlement brings the recipient, agreed terms, execution and result into one record. Start with the lifecycle, then review integration and operating controls.',
    body: `<section><h2>From instruction to final record</h2><ol class="resource-steps"><li><h3>Define the recipient and terms</h3><p>Identify a verified Indian beneficiary, the required recipient INR amount, payment purpose and funding currency. Link the instruction to a commercial reference.</p></li><li><h3>Check requirements before authorization</h3><p>Preflight identifies outstanding requirements. Review the quote, fees and validity, then authorize the agreed settlement under the workspace policy.</p></li><li><h3>Observe execution</h3><p>Funding, payout execution and provider observations are tracked against the instruction. Exceptions need an explicit resolution rather than an assumed success.</p></li><li><h3>Reconcile and retain the result</h3><p>Match delivery evidence to the expected amount and recipient. A settled outcome is supported by reconciliation and a final receipt.</p></li></ol></section>
      <section><h2>Five customer-facing states</h2><dl class="resource-definitions"><div><dt>Ready</dt><dd>The requirements are satisfied; execution has not been authorized.</dd></div><div><dt>Settling</dt><dd>The authorized settlement is progressing through execution.</dd></div><div><dt>Settled</dt><dd>Delivery and reconciliation support the final result; the receipt is available.</dd></div><div><dt>Action required</dt><dd>A stated requirement or exception needs attention.</dd></div><div><dt>Cancelled</dt><dd>The settlement did not complete and has a recorded resolution.</dd></div></dl><p>The demo illustrates these states. It does not represent a live provider connection or a completed financial transaction.</p></section>
      <section><h2>Explore the operating model</h2><div class="resource-grid"><a class="resource-card" href="/docs/integration"><h3>Provider integration</h3><p>Funding, provider execution, status observations and evidence boundaries.</p><span>Read the integration guide →</span></a><a class="resource-card" href="/developers"><h3>Platform integration</h3><p>Beneficiaries, quotes, authorization, safe retries and event delivery.</p><span>Explore developer workflows →</span></a><a class="resource-card" href="/security"><h3>Operating controls</h3><p>Workspace scope, permissions, financial integrity and demo access.</p><span>Review the security model →</span></a><a class="resource-card" href="/docs/reconciliation"><h3>Reconciliation and receipts</h3><p>Match delivery evidence to the instruction and retain the final record.</p><span>Review settlement evidence →</span></a></div></section>`,
  },
  {
    path: '/docs/integration', label: 'Provider integration', parent: '/docs', eyebrow: 'Provider integration',
    title: 'Provider Integration & Settlement Evidence | INRSettle',
    description: 'Review provider boundaries for India settlement: route requirements, funding, payout execution, verified status observations and reconciliation evidence.',
    heading: 'Connect the route.<br><span>Preserve the operating record.</span>',
    intro: 'Bank and payout providers, funding methods and evidence sources have different responsibilities. Agree those boundaries before an instruction can execute.',
    body: `<section><h2>Confirm the route before connecting</h2><p>Define business eligibility, payment purpose, destination requirements, currencies, limits, fees and operating windows with the relevant parties. A discovery selection on the website is a proposed workflow, not confirmation that a route is available.</p><div class="resource-grid"><article><h3>Funding responsibility</h3><p>Identify who supplies funding, when it must be available and which record confirms the funding position.</p></article><article><h3>Execution responsibility</h3><p>Agree the provider responsible for the Indian bank leg, its destination validation and its submission and cancellation boundaries.</p></article></div></section>
      <section><h2>Keep execution observable</h2><ol class="resource-steps"><li><h3>Record the instruction</h3><p>Bind beneficiary, recipient amount, commercial purpose and agreed terms before provider submission. Retain the external reference and the identity of the authorizing actor.</p></li><li><h3>Track provider observations</h3><p>Preserve provider references and observed outcomes. Verify the origin of incoming status information and handle repeat events without creating a new payout.</p></li><li><h3>Resolve uncertainty deliberately</h3><p>A timeout does not establish whether a payout happened. Confirm the provider outcome before retrying or selecting an alternate route.</p></li><li><h3>Match delivery evidence</h3><p>Reconcile the recipient, amount and relevant provider references. A provider success message alone is not the final settlement record.</p></li></ol></section>
      <section><h2>Validate the handoff together</h2><p>Integration review should cover representative success, rejection, duplicate-event and uncertain-outcome scenarios. Agree how your team receives status, handles action-required cases and stores the final receipt.</p><p>This guide describes the integration model. Provider activation, production access and the available route are confirmed during onboarding.</p><a class="resource-link" href="/developers">Explore platform integration →</a></section>`,
  },
  {
    path: '/docs/reconciliation', label: 'Reconciliation', parent: '/docs', eyebrow: 'Settlement evidence',
    title: 'Settlement Reconciliation & Receipts | INRSettle',
    description: 'Understand settlement reconciliation with INRSettle: match delivery evidence to the expected recipient and INR amount, resolve exceptions and retain receipts.',
    heading: 'Match the evidence.<br><span>Retain the final record.</span>',
    intro: 'A provider status is an observation. Reconciliation connects the expected settlement to delivery evidence and a record your operations team can trace.',
    body: `<section><h2>Start with the authorized instruction</h2><p>Keep the beneficiary, required recipient INR amount, payment purpose and agreed terms together. Your own external reference connects this instruction to your commercial records.</p><p>Compare the observed outcome with those terms. An accepted provider request or a successful status message does not, on its own, establish the final reconciled result.</p></section>
      <section><h2>Build a traceable evidence chain</h2><ol class="resource-steps"><li><h3>Preserve the provider reference</h3><p>Record which payout the provider observed, when the observation arrived and which instruction it relates to. Verify the source of status events.</p></li><li><h3>Match the delivery details</h3><p>Check the recipient, expected amount and relevant provider or bank reference. Keep the evidence source attached to the reconciliation record.</p></li><li><h3>Resolve mismatches explicitly</h3><p>A partial credit, rejection or uncertain outcome needs a stated resolution. Do not replace the original instruction or infer a new payout from a timeout.</p></li><li><h3>Retain the final receipt</h3><p>Once the settlement has a supported final result, keep the receipt and its settlement reference with your operational records.</p></li></ol></section>
      <section><h2>Agree your reconciliation handoff</h2><p>Discuss evidence sources, reference mapping, exception ownership and the record your team needs after settlement. Funding methods, provider responsibilities and production availability are confirmed for the proposed route during onboarding.</p><p>The public workspace contains illustrative records. A demo receipt is not evidence of a financial transaction.</p><a class="resource-link" href="/docs/integration">Review provider responsibilities →</a></section>`,
  },
  {
    path: '/security', label: 'Security', eyebrow: 'Operating controls',
    title: 'Settlement Security & Operating Controls | INRSettle',
    description: 'Review INRSettle security principles for workspace isolation, settlement permissions, financial integrity, event verification and private demo access.',
    heading: 'Clear permissions.<br><span>Traceable settlement decisions.</span>',
    intro: 'The security model covers both access and financial integrity: who can act, which instruction they authorize and what evidence supports the result.',
    body: `<section><h2>The product security model</h2><div class="resource-grid"><article><h3>Workspace isolation</h3><p>Scope access to the authenticated workspace and environment. A request should not expose another workspace’s records.</p></article><article><h3>Separate permissions</h3><p>Creating an instruction, authorizing settlement and administering a workspace are separate capabilities. Separation of duties follows the workspace policy.</p></article><article><h3>Financial integrity</h3><p>Authorized terms stay attached to the instruction. Status changes, execution observations and reconciliation need a traceable record.</p></article><article><h3>Integration trust</h3><p>Keep credentials on server boundaries, verify incoming events and use idempotency for retryable operations.</p></article></div><p>These are product design principles. Deployment controls and assurance evidence should be reviewed for the specific engagement with our team.</p></section>
      <section><h2>What the public preview provides</h2><p>The website workspace runs on demonstration data. It has no connected payment provider or financial authorization and does not move money.</p><p>Private walkthroughs can use a shared access code enforced before workspace files are served. That preview gate is not customer account authentication or proof of production readiness.</p></section>
      <section><h2>Discuss security requirements</h2><p>Contact our team to review your access model, data handling, operating responsibilities and integration acceptance criteria. This page does not claim a certification, regulatory approval or independently audited production deployment.</p><p>For an initial inquiry, share business context only. Do not submit account credentials, identity documents, bank details or sensitive customer records.</p><a class="resource-link" href="/privacy">Read about inquiry privacy →</a></section>`,
  },
  {
    path: '/privacy', label: 'Inquiry privacy', eyebrow: 'Business inquiries',
    title: 'Business Inquiry Privacy | INRSettle',
    description: 'Learn what to share in an INRSettle business inquiry, how the team receives your contact details and how to request a correction or deletion.',
    heading: 'Start a conversation.<br><span>Share only what is needed.</span>',
    intro: 'The inquiry form is for business contact details and a short description of your settlement needs.',
    body: `<section><h2>Information in an inquiry</h2><p>The form asks for your name, work email, company, inquiry topic and message. If you attach a workflow from the planner, the selected direction, currencies, use case and indicative volume are included as business context.</p><p>Do not include bank account details, identity documents, credentials or sensitive customer information.</p></section>
      <section><h2>Delivery and response</h2><p>Your inquiry is submitted through the website to the INRSettle team using the configured delivery service: Telegram or email. The team uses your work email to reply.</p><p>Submission is confirmed after the delivery service acknowledges the inquiry. If confirmation fails, the form retains your details so you can retry. The public workspace and planner are demonstrations; sending an inquiry does not create a payment or account.</p></section>
      <section><h2>Questions, corrections and deletion</h2><p>Inquiries are handled as business correspondence. For questions about your inquiry, a correction or a deletion request, contact <a href="mailto:info@inrsettle.com">info@inrsettle.com</a>.</p><p>This page covers the public business inquiry form. Data handling and contractual requirements for a production engagement are agreed separately.</p></section>`,
  },
];
